language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: malimehul.dev@gmail.com
  api_key:
    secure: zgd9vfbRK155eh0IK860UmLNegV1QpWPIcEq7nfvfsqL6P0pMxpewdCs3/fOliggupEdawdzE4B/Orp9L1t104oUMBSoP2fPG4PTNvcjQ16ytaQxpFuheNiXZCpO0hY2Ep1K6h6aN78wtaPv29KGjbr3uIqUsIDf0p/Km/63NDlFDXWqA8rVcgXW4OFWkEetSlrNAGabZzDrDZSEK/t6BePoLnvJMUXsklUxbHtUTcQVrqxfq7KFuVhhUzQGBrzg5ZJWqI0Kny4KAeYUyUvOEO1ySOkkguoyCdqyFSDTKibqDHjTdp0ZayCCp/AVOwvaK38mvoDy1iYTr8ywZ/XiECYgvdp/xpXH4z640Db5N0QU7tZdp2Vt+m9eyeF8SsdOnpnEDql7BkObQaWgc5GZTJaaY+GUNyGUDkkXJ/0Yr0xWhVk7+/uXuxWTbwlgpXtU5dVObu8KuEgyny9hCQtaSdT6+QD28M+Y+rmg5JDRZjgOJ3LIaRNLNGPN/ufb1v3NvX0zSpFZiOvb9+Nk+tsg8huwPIyGenQFB8jlKHjF/ni7FVulcBSqyPFrZq5tTVpyoYI7aEXSjRE9YRfnzx+zw/LIDSSuft+xgknTUtovbJmrowojIoYtQZmvTn1rwEpRgjkgn7CDAbgL5LmJPSG9z+CCoTttZmfwcxFsEbACQ0g=
  on:
    tags: true
    repo: mehulmali/api-npm-pack
